import { chromium } from 'playwright';
const url = 'https://spring-liz-estate-taxation.trycloudflare.com';
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1280, height: 720 } });
const p = await c.newPage();
console.log('goto', url);
await p.goto(url, { waitUntil: 'domcontentloaded', timeout: 30000 });
await p.waitForTimeout(3000);
await p.screenshot({ path: '/home/runner/work/aiplay/aiplay/project/screenshots/final-menu.png' });
console.log('final-menu captured');
await p.evaluate(()=>{ const el=document.getElementById('startOverlay'); if(el) el.style.display='none'; });
await p.waitForTimeout(3500);
await p.screenshot({ path: '/home/runner/work/aiplay/aiplay/project/screenshots/final-arena.png' });
console.log('final-arena captured');
const q = await c.newPage();
await q.goto('http://127.0.0.1:8765/', { waitUntil: 'domcontentloaded' });
await q.waitForTimeout(2000);
await q.screenshot({ path: '/home/runner/work/aiplay/aiplay/project/screenshots/final-crate-ab.png' });
console.log('final-crate-ab captured');
await b.close();
console.log('done');
