const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),scoreEl=document.querySelector('#score'),timerEl=document.querySelector('#timer'),message=document.querySelector('#message'),title=document.querySelector('#message-title'),kicker=document.querySelector('#message-kicker'),copy=document.querySelector('#message-copy');
const W=960,H=516,TARGET=10,keys={};let dpr=1,player,shards,clouds,stars,score,timeLeft,last=0,started=false,ended=false,raf,touchTarget=null;
const rand=(a,b)=>a+Math.random()*(b-a);function resize(){dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
function reset(){cancelAnimationFrame(raf);score=0;timeLeft=60;ended=false;started=false;player={x:W/2,y:H/2,r:16,vx:0,vy:0};shards=Array.from({length:TARGET},(_,i)=>({x:rand(70,W-70),y:rand(70,H-60),phase:rand(0,7),got:false,n:i}));clouds=[{x:160,y:145,r:38,vx:22,vy:7},{x:480,y:365,r:47,vx:-27,vy:-5},{x:800,y:170,r:34,vx:18,vy:8},{x:665,y:90,r:25,vx:-15,vy:13}];stars=Array.from({length:65},()=>({x:rand(0,W),y:rand(0,H),r:rand(.4,1.8),a:rand(.25,.85)}));scoreEl.textContent=0;timerEl.textContent=60;message.hidden=true;draw();}
function draw(){ctx.clearRect(0,0,W,H);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#17184a');g.addColorStop(1,'#0b1230');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);stars.forEach(s=>{ctx.globalAlpha=s.a;ctx.fillStyle='#e5dcff';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill()});ctx.globalAlpha=1;ctx.fillStyle='rgba(122,108,202,.1)';ctx.beginPath();ctx.ellipse(180,480,320,58,0,0,7);ctx.fill();ctx.fillStyle='rgba(105,88,184,.09)';ctx.beginPath();ctx.ellipse(800,500,330,72,0,0,7);ctx.fill();shards.forEach(s=>{if(s.got)return;let bob=Math.sin(s.phase+performance.now()/600)*4;ctx.save();ctx.translate(s.x,s.y+bob);ctx.shadowBlur=18;ctx.shadowColor='#b9a5ff';ctx.fillStyle='#cfc5ff';ctx.rotate(Math.PI/4);ctx.fillRect(-7,-7,14,14);ctx.restore()});clouds.forEach(c=>{ctx.save();ctx.translate(c.x,c.y);ctx.shadowBlur=16;ctx.shadowColor='rgba(0,0,0,.45)';ctx.fillStyle='rgba(101,105,165,.72)';ctx.beginPath();ctx.arc(-c.r*.55,4,c.r*.55,0,7);ctx.arc(0,-c.r*.15,c.r*.75,0,7);ctx.arc(c.r*.58,7,c.r*.48,0,7);ctx.fill();ctx.restore()});drawLantern();}
function drawLantern(){ctx.save();ctx.translate(player.x,player.y);let glow=ctx.createRadialGradient(0,0,3,0,0,45);glow.addColorStop(0,'rgba(255,220,133,.55)');glow.addColorStop(1,'rgba(255,205,105,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(0,0,45,0,7);ctx.fill();ctx.shadowBlur=21;ctx.shadowColor='#ffd47b';ctx.fillStyle='#ffd477';ctx.beginPath();ctx.arc(0,0,11,0,7);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#fff4c2';ctx.lineWidth=2;ctx.stroke();ctx.strokeStyle='#f4b86c';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,15,-2.5, -.65);ctx.arc(0,0,15,.65,2.5);ctx.stroke();ctx.restore()}
function finish(win){ended=true;started=false;kicker.textContent=win?'MISSION COMPLETE':'NIGHT LOST';title.textContent=win?'The night is yours.':'The clouds caught your light.';copy.textContent=win?'Every shard found. The moon is glowing brighter.':'You were so close. Try a quieter route through the clouds.';message.hidden=false;}
function update(dt){let ax=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),ay=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(touchTarget){const tx=touchTarget.x-player.x,ty=touchTarget.y-player.y,d=Math.hypot(tx,ty)||1;ax=tx/d;ay=ty/d}if(ax||ay)started=true;player.vx+=(ax*340-player.vx)*Math.min(1,dt*8);player.vy+=(ay*340-player.vy)*Math.min(1,dt*8);player.x=Math.max(25,Math.min(W-25,player.x+player.vx*dt));player.y=Math.max(25,Math.min(H-25,player.y+player.vy*dt));clouds.forEach(c=>{c.x+=c.vx*dt;c.y+=c.vy*dt;if(c.x<-90||c.x>W+90)c.vx*=-1;if(c.y<-80||c.y>H+80)c.vy*=-1});shards.forEach(s=>{if(!s.got&&Math.hypot(player.x-s.x,player.y-s.y)<25){s.got=true;score++;scoreEl.textContent=score;if(score>=TARGET)finish(true)}});clouds.forEach(c=>{if(Math.hypot(player.x-c.x,player.y-c.y)<c.r+12)finish(false)});timeLeft=Math.max(0,timeLeft-dt);timerEl.textContent=Math.ceil(timeLeft);if(timeLeft<=0&&!ended)finish(false)}
function loop(t){let dt=Math.min(.04,(t-last)/1000||0);last=t;if(!ended){update(dt);draw()}else draw();raf=requestAnimationFrame(loop)}
function steerFromPointer(e){const box=canvas.getBoundingClientRect();touchTarget={x:(e.clientX-box.left)*W/box.width,y:(e.clientY-box.top)*H/box.height}}
canvas.addEventListener('pointerdown',e=>{if(!ended){canvas.setPointerCapture(e.pointerId);steerFromPointer(e)}});canvas.addEventListener('pointermove',e=>{if(e.buttons&&!ended)steerFromPointer(e)});canvas.addEventListener('pointerup',()=>{touchTarget=null});canvas.addEventListener('pointercancel',()=>{touchTarget=null});
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys[e.key]=true});addEventListener('keyup',e=>keys[e.key]=false);document.querySelector('#restart').onclick=reset;document.querySelector('#play-again').onclick=reset;addEventListener('resize',resize);resize();reset();raf=requestAnimationFrame(loop);
