import { chromium } from 'playwright';
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1280, height: 720 } });
const p = await c.newPage();
await p.goto('http://127.0.0.1:3000/', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(2500);
await p.screenshot({ path: '/home/runner/work/aiplay/aiplay/project/screenshots/final-menu.png' });
console.log('menu ok');
await p.evaluate(()=>{ document.getElementById('startOverlay').style.display='none'; });
await p.waitForTimeout(800);
await p.screenshot({ path: '/home/runner/work/aiplay/aiplay/project/screenshots/final-arena.png' });
console.log('arena ok');
const q = await c.newPage();
await q.goto('http://127.0.0.1:8765/', { waitUntil: 'domcontentloaded' });
await q.waitForTimeout(2000);
await q.screenshot({ path: '/home/runner/work/aiplay/aiplay/project/screenshots/final-crate-ab.png' });
console.log('ab ok');
await b.close();
console.log('done');
